### ISSUE TITLE
Wrong link in https://vaadin.com/tutorials/migrating-java-swing-to-web-with-vaadin

### ISSUE THREAD

**Issue by tdq** [vaadin-learning-center/learning-content#145]
The "Github repository" at the end of https://vaadin.com/tutorials/migrating-java-swing-to-web-with-vaadin links to https://github.com/vaadin-learning-center/vaadin-for-swing-developers, which does not exist. It should probably be https://github.com/vaadin-learning-center/vaadin-platform-for-swing-developers/ instead.

**Comment by marcushellberg** [comment]
Thanks. I already fixed this yesterday, looks like it's working now.
