### ISSUE TITLE
Old screenshot in main Flow tutorial

### ISSUE THREAD

**Issue by jouni** [vaadin-learning-center/learning-content#33]
The screenshot of the resulting app looks different from the real product.

- The buttons are no longer on white background with shadows
- The text input background color is darker nowadays (better contrast)
- The fields do not have any space between them (they should)
- The dropdown icon in combo box is outdated here
- The grid does not have row borders (it should)

![screen_shot_2018-12-17_at_15 18 30](https://user-images.githubusercontent.com/66382/51321258-fcb3ad00-1a6a-11e9-8d13-98f2662d5242.png)

**Comment by alejandro-du** [comment]
Fixed with the latest improvements to the tutorial.
