### ISSUE TITLE
"Calling Java from JavaScript" tutorial do not have og_image defined

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin-learning-center/learning-content#68]

**Comment by marcushellberg** [comment]
The site should use the thumbnail picture automatically for og_image. It is defined as:  https://github.com/vaadin-learning-center/learning-content/blob/development/tutorials/calling-java-from-javascript/images/calling-java-js-thumbnail.png

**Comment by fluorumlabs** [comment]
Well, now it does I believe. Yet I would like to point out (without any offence), that it wasn’t specified in the original requirements ;)
